### ISSUE TITLE
Dynamic Temperature Tab's Temperature Threshold Numeric Inputs do not get visually updated after a GUI Restart

### ISSUE THREAD

**Issue by PXDiv** [PXDiv/Div-Acer-Manager#2]
>    ...
>     Temperature Settings UI: There seems to be a UI bug related to temperature settings.
>         I can set the values, and they are correctly saved in the configuration file.
>         However, after closing and reopening the application, the UI fields for temperature do not show the saved values; they seem to reset visually (though the saved config values are still used by the backend, presumably).
>         See attached image showing the discrepancy: 
> 
> https://github.com/user-attachments/assets/e4788b73-2d3c-4fc9-8877-82a0e4fa8262
> 
> 
> ...

 _Originally posted by @MematiBas42 in [#1](https://github.com/PXDiv/Div-Acer-Manager/issues/1#issuecomment-2786165097)_

**Comment by PXDiv** [comment]
This Issue has been fixed now. Please Update the application
Closing Issue page

**Comment by MematiBas42** [comment]
Works perfect! Thanks for your work <3

**Comment by PXDiv** [comment]
> Works perfect! Thanks for your work <3

Glad to hear that 😄, 
can you please tell me your laptop model and distro so that I can add it to the tested models.
Thank you again

**Comment by MematiBas42** [comment]
Update:

    I encountered an issue recently, though I'm not certain of the exact cause. After several system restarts, my laptop's fan speed became stuck at its minimum setting.

    Troubleshooting Steps Taken:

        I immediately set the default profile to 'powersaving' (though this didn't resolve the fan issue).
        I then attempted reinstalling both an older release and the latest release of [mention the software/driver if relevant], but the fan speed problem persisted.

    Resolution:
    I restored a system snapshot created two days prior. Since restoring the snapshot, the fan control is functioning normally again.

    Current Status:
    Due to the snapshot restore, I suspect I am now running a previous version of [the software/driver].
    My laptop model is: Acer Nitro V 15 ANV15-51-567U.

    Next Steps:
    I plan to attempt the update to the latest version again in 15 minutes. I will report back here if the fan issue reappears after updating.

**Comment by MematiBas42** [comment]
Edit: Tried again issue persist.

what i did is download latest version, 
➜ chmod +x SetupDrivers.sh
➜ sudo ./SetupDrivers.sh
select option update (3)
reboot directly

efter boots up
➜ stress-ng --cpu 12 --cpu-load 60 --timeout 400

fan always at lowest

**Comment by MematiBas42** [comment]
complately removed, reboot windows play with nitro sense, reboot Arch stock fan config came back, reinstall updated DAM-FC still fan changes unable to perform, rolling back to 0.4.5 works without issues, 0.4.6 is not working as expected. Acer Nitro V 15 ANV15-51-567U

**Comment by MematiBas42** [comment]
~/İndirilenler/DivAcerManager 0.4.5
➜ sudo snapper -c root undochange 63..0
create:10 modify:26 delete:15

~/İndirilenler/DivAcerManager 0.4.5 took 8s
➜ sudo systemctl restart dam-fan-controls-daemon.service

immediately fixes rolling back with snapshot and restart service. 


`~/İndirilenler/DivAcerManager 0.4.5 took 3s
➜ sudo snapper -c root status 63..64
c..... /etc/tuned/active_profile
c..... /etc/tuned/ppd_base_profile
c..... /etc/.updated
-..... /o3312858-25072-0
-..... /o3312859-25072-0
-..... /o3312860-25072-0
-..... /o3312861-25072-0
-..... /o3312862-25072-0
-..... /o3312863-25072-0
-..... /opt/dam-fan-controls/DAMFC_daemon
+..... /opt/dam-fan-controls/DAMFC_daemon.bak
.p.... /opt/dam-fan-controls/icons/dam-fan-controls.png
+..... /root/.cache/ksycoca6_tr_ZO9BCAqxRsYOeb+jgSNOcFvO9+Y=
c..... /root/.cache/mesa_shader_cache_db/part0/mesa_cache.idx
+..... /root/.net/DAM-FC/mlXsf1Qzxcx8kCsuMLhbX7p0NXoi5jE=
+..... /root/.net/DAM-FC/mlXsf1Qzxcx8kCsuMLhbX7p0NXoi5jE=/libHarfBuzzSharp.so
+..... /root/.net/DAM-FC/mlXsf1Qzxcx8kCsuMLhbX7p0NXoi5jE=/libSkiaSharp.so
c..... /usr/local/bin/DAM-FC
+..... /usr/share/applications/dam-fan-controls.desktop
.p.... /usr/share/applications/mimeinfo.cache
.p.... /usr/share/icons/hicolor/icon-theme.cache
c..... /usr/share/iptables/simple_firewall.rules
c..... /var/lib/alsa/asound.state
c..... /var/lib/bluetooth/E4:60:17:03:B3:5C/attributes
c..... /var/lib/NetworkManager/timestamps
c..... /var/lib/plymouth/boot-duration
c..... /var/lib/sddm/.cache/mesa_shader_cache_db/part0/mesa_cache.idx
c..... /var/lib/sddm/.cache/sddm-greeter-qt6/qtpipelinecache-x86_64-little_endian-lp64/qqpc_opengl
c..... /var/lib/sddm/.local/state/wireplumber/stream-properties
+..... /var/lib/systemd/coredump/core.ark.1000.6557f71c6846463c893df7a9ca880a6f.97474.1744311261000000.zst
+..... /var/lib/systemd/coredump/core.DAM-FC.0.9615d82fe3ef47939f07d1e5ae6b705d.3203.1744311543000000.zst
c..... /var/lib/systemd/random-seed
c..... /var/lib/upower/history-charge-generic_id.dat
c..... /var/lib/upower/history-rate-generic_id.dat
c..... /var/lib/upower/history-time-empty-generic_id.dat
c..... /var/lib/upower/history-time-full-generic_id.dat
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-bluetooth.service-EdjcCd
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-bluetooth.service-EdjcCd/tmp
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-dbus-broker.service-vhoKIf
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-dbus-broker.service-vhoKIf/tmp
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-polkit.service-iQ4sGd
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-polkit.service-iQ4sGd/tmp
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-systemd-logind.service-muZZd4
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-systemd-logind.service-muZZd4/tmp
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-upower.service-09tkfV
-..... /var/tmp/systemd-private-6557f71c6846463c893df7a9ca880a6f-upower.service-09tkfV/tmp
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-bluetooth.service-CtI4Ve
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-bluetooth.service-CtI4Ve/tmp
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-dbus-broker.service-aRdg5j
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-dbus-broker.service-aRdg5j/tmp
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-polkit.service-uLEjKm
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-polkit.service-uLEjKm/tmp
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-systemd-logind.service-Dkyff9
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-systemd-logind.service-Dkyff9/tmp
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-upower.service-KCeGbo
+..... /var/tmp/systemd-private-9615d82fe3ef47939f07d1e5ae6b705d-upower.service-KCeGbo/tmp
c..... /var/.updated

~/İndirilenler/DivAcerManager 0.4.5
➜`

**Comment by PXDiv** [comment]
I think I know the fix, 
Just go to the advanced tab, Clean and unload Drivers, Compile the drivers, then reload them
This should fix it
